### ISSUE TITLE
On enable error:

### ISSUE THREAD

**Issue by x3mp** [blendernc/blendernc-zip-install#2]
![image](https://user-images.githubusercontent.com/12957439/152957210-8b7f7763-5691-4f74-b9dc-53035f49f3b2.png)
See the image above for the error.

**Comment by josuemtzmo** [comment]
Hello @UnrealPixel, it seems that you don't have all the dependencies installed in Blender. 

Please follow the instructions described at:
https://blendernc.readthedocs.io/en/latest/install.html

if you are unable to install the requirements from the file, you can simply run:
```
set BLENDERPY=D:/Programma's/Blender/2.92/python/bin/python.exe
%BLENDERPY%-m ensurepip
%BLENDERPY% -m pip install -r requirements.txt
$BLENDERPY -m pip install numpy cython zarr ecmwflibs cfgrib xarray cmocean matplotlib dask dask scipy netCDF4 toolz pooch psutil
```
Make sure to replace the `XXX` with the versions you are using. I'm not sure if this is the path to the python installed in blender: `D:/Programma's/Blender/2.92/python/bin/python.exe`

**Comment by x3mp** [comment]
I tried to install these dependancies but windows doesnt pick the commanda it just returns an error and if i execute them through python it does the same.

**Comment by josuemtzmo** [comment]
> I tried to install these dependancies but windows doesnt pick the commanda it just returns an error and if i execute them through python it does the same.

Are you using the python that comes with Blender to install the modules?

**Comment by x3mp** [comment]
> > I tried to install these dependancies but windows doesnt pick the commanda it just returns an error and if i execute them through python it does the same.
> 
> Are you using the python that comes with Blender to install the modules?

Yes, I'm starting the python environment from the one provided by Blender...

**Comment by x3mp** [comment]
Solved, please fix in the documentation:
`%BLENDERPY%-m ensurepip` needs to be: `%BLENDERPY% -m ensurepip`

There is missing a space before the -m so the command isn't recognized. My bad!

**Comment by x3mp** [comment]
I am however still getting an error while installing dependencies.
https://www.toptal.com/developers/hastebin/jajimumaxa.sql

**Comment by josuemtzmo** [comment]
Thanks for that, I will fix it in the documentation.

**Comment by josuemtzmo** [comment]
Is the error you get from `%BLENDERPY% -m ensurepip` or from installing the requirements?

**Comment by x3mp** [comment]
I did the commands in regular windows prompt. When I try to execute `set BLENDERPY=D:\Programma's\blender\2.92\python\bin\python.exe` in the blender provided python.exe it gives me an error for invalid syntax.

> Is the error you get from `%BLENDERPY% -m ensurepip` or from installing the requirements?

This error happens when I execute: `%BLENDERPY% -m pip install -r requirements.txt`
I made a requirements.txt file with all the dependencies. I add the path before the requirements.txt text in the command.

**Comment by josuemtzmo** [comment]
Ok, can you try to directly do something like:
`D:\Programma's\blender\2.92\python\bin\python.exe -m ensurepip`
Can you also attach the output of that command?

**Comment by x3mp** [comment]
> Ok, can you try to directly do something like: `D:\Programma's\blender\2.92\python\bin\python.exe -m ensurepip` Can you also attach the output of that command?

Thats not the issue, because when I execute `%BLENDERPY% -m ensurepip` it returns:
`C:\Users\Beheerder>%BLENDERPY% -m ensurepip
Looking in links: c:\Users\BEHEER~1\AppData\Local\Temp\tmp5yli3i_h
Requirement already satisfied: setuptools in d:\programma's\blender\2.92\python\lib\site-packages (41.2.0)
Requirement already satisfied: pip in d:\programma's\blender\2.92\python\lib\site-packages (19.2.3)`

**Comment by josuemtzmo** [comment]
Ok, what about:

```
%BLENDERPY% -m pip install numpy cython zarr ecmwflibs cfgrib xarray cmocean matplotlib dask dask scipy netCDF4 toolz pooch psutil
```

**Comment by x3mp** [comment]
> 

Currently executing this with a direct path instead of `%BLENDERPY%`

**Comment by x3mp** [comment]
Result:
https://www.toptal.com/developers/hastebin/jeqalufibe.sql

**Comment by josuemtzmo** [comment]
This error seems to be unrelated to BlenderNC, it has to do wit a GDAL library. Could you send me the full error? to figure out which library requires that dependancy?

**Comment by x3mp** [comment]
> This error seems to be unrelated to BlenderNC, it has to do wit a GDAL library. Could you send me the full error? to figure out which library requires that dependancy?

That is the full error...

**Comment by josuemtzmo** [comment]
Ok, I honestly have no idea, it seems to be the installation of a dependency of `xarray`, `rasterio` the one generating the issue. My only hack to solve this issue, will be to install the dependencies in a different environment and then link them to blender, see below:
First get the python version of blender:
```
D:\Programma's\blender\2.92\python\bin\python.exe --version
```
Then create with conda a new environment using the same python version, and install all the requirements there, doing:
```
conda install --file requirements.txt
```
Finally, you can link the libraries by doing something like:
```
cd /path/to/blender/2.92/scripts/modules
mklink PATH_PYTHON/lib/python$(PYTHON_VERSION)/site-packages/* .
```
your PATH_PYTHON should be where conda installed the environment.

**Comment by x3mp** [comment]
`conda install --file requirements.txt`

Isn't seen as a valid command. Am I missing something?

**Comment by josuemtzmo** [comment]
So `conda` is a package manager, it will install all the requirements, but you will need to install it:
https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html
You can also create a new environment within python and install all the dependencies and that should work too, but I believe you will end up with the same error, as it seems that `rasterio` needs some specific versions GDAL library to run in Windows.
